// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pg "github.com/go-pg/pg/v9"
	mock "github.com/stretchr/testify/mock"
)

// Databaser is an autogenerated mock type for the Databaser type
type Databaser struct {
	mock.Mock
}

// DB provides a mock function with given fields:
func (_m *Databaser) DB() *pg.DB {
	ret := _m.Called()

	var r0 *pg.DB
	if rf, ok := ret.Get(0).(func() *pg.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pg.DB)
		}
	}

	return r0
}

// TenantDB provides a mock function with given fields: schema
func (_m *Databaser) TenantDB(schema string) *pg.DB {
	ret := _m.Called(schema)

	var r0 *pg.DB
	if rf, ok := ret.Get(0).(func(string) *pg.DB); ok {
		r0 = rf(schema)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pg.DB)
		}
	}

	return r0
}
