// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// DBContext is an autogenerated mock type for the DBContext type
type DBContext struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *DBContext) Get(key string) interface{} {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Request provides a mock function with given fields:
func (_m *DBContext) Request() *http.Request {
	ret := _m.Called()

	var r0 *http.Request
	if rf, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	return r0
}

// Set provides a mock function with given fields: key, val
func (_m *DBContext) Set(key string, val interface{}) {
	_m.Called(key, val)
}
